export type LogType =
  | "auth"
  | "ai-action"
  | "admin"
  | "approval"
  | "system";

export type LogResult = "success" | "blocked" | "failed";

export type LogEntry = {
  id: string;
  at: string; // ISO timestamp, sortable
  type: LogType;
  actorKind: "human" | "ai" | "system";
  actorName: string;
  actorMeta?: string;
  action: string;
  target?: string;
  ip: string;
  city: string;
  region: string;
  country: string; // human-readable
  countryCode: string; // ISO
  flag: string;
  device: string;
  browser: string;
  language: string;
  result: LogResult;
};

export const LOGS: LogEntry[] = [
  {
    id: "log_0001",
    at: "2026-05-12T14:23:48Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Iris",
    actorMeta: "Inbound Sales Closer",
    action: "Drafted email reply",
    target: "Lead · ada@example.com · 'free returns' addition",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0002",
    at: "2026-05-12T14:21:11Z",
    type: "approval",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Approved refund",
    target: "Order #1843 · €120 · Cyrus (Customer Support)",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0003",
    at: "2026-05-12T14:18:02Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Soren",
    actorMeta: "Social Media Manager",
    action: "Scheduled 3 Instagram posts",
    target: "Week of May 12 · brand · @northway.goods",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0004",
    at: "2026-05-12T13:51:47Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Cyrus",
    actorMeta: "Customer Support",
    action: "Escalated to human",
    target: "Marie Janssen · WhatsApp · order #1843",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "DE",
    result: "success",
  },
  {
    id: "log_0005",
    at: "2026-05-12T08:23:14Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Login · OTP verified",
    target: "Web session",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0006",
    at: "2026-05-12T08:22:42Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "OTP requested",
    target: "Email · test@mail.com",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0007",
    at: "2026-05-11T22:48:09Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Login · biometric",
    target: "Mobile session · Face ID",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "iPhone 15 Pro",
    browser: "Staffbix iOS app",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0008",
    at: "2026-05-11T15:14:33Z",
    type: "admin",
    actorKind: "human",
    actorName: "Ayşe Nehir",
    actorMeta: "Admin",
    action: "Hired AI worker",
    target: "Bea (Bookkeeping Assistant)",
    ip: "94.55.182.27",
    city: "Ankara",
    region: "Ankara",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Air",
    browser: "Safari 17.4",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0009",
    at: "2026-05-11T11:42:51Z",
    type: "admin",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Updated Brand Bible · Policies",
    target: "Returns: 30 days → 45 days",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0010",
    at: "2026-05-11T09:08:21Z",
    type: "approval",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Rejected with feedback",
    target: "Adi (Ad Manager) · Boost Reels post $80",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "iPhone 15 Pro",
    browser: "Staffbix iOS app",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0011",
    at: "2026-05-10T21:14:09Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "New device login alert sent",
    target: "Linux · Firefox · Berlin",
    ip: "94.55.118.42",
    city: "Berlin",
    region: "Berlin",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Linux desktop",
    browser: "Firefox 125",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0012",
    at: "2026-05-10T11:47:33Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Spending cap reached",
    target: "Adi (Ad Manager) · daily cap $200",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "blocked",
  },
  {
    id: "log_0013",
    at: "2026-05-10T08:00:00Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Daily briefing sent",
    target: "test@mail.com",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0014",
    at: "2026-05-09T18:22:17Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Sage",
    actorMeta: "SEO Specialist",
    action: "Published blog post",
    target: "'Why solo founders skip CRMs' · 1,847 words",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0015",
    at: "2026-05-09T14:30:55Z",
    type: "admin",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Invited team member",
    target: "rachel@northway.example · Editor role",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0016",
    at: "2026-05-09T10:12:09Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Ezra",
    actorMeta: "Email Marketer",
    action: "Sent welcome sequence",
    target: "18 new subscribers · welcome-v3",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0017",
    at: "2026-05-08T16:48:42Z",
    type: "auth",
    actorKind: "human",
    actorName: "Mert Kıvanç",
    actorMeta: "Editor",
    action: "Failed login · invalid password",
    ip: "212.156.91.4",
    city: "Izmir",
    region: "Izmir",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Air",
    browser: "Chrome 124",
    language: "TR",
    result: "failed",
  },
  {
    id: "log_0018",
    at: "2026-05-08T14:34:11Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Password changed",
    target: "All sessions invalidated",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0019",
    at: "2026-05-08T09:22:08Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Subscription renewed",
    target: "Business plan · $399 · Visa 6411",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0020",
    at: "2026-05-07T17:33:01Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Cora",
    actorMeta: "Content Writer",
    action: "Rewrote 12 product descriptions",
    target: "Outdoor gear · seasonal refresh",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0021",
    at: "2026-05-07T11:14:55Z",
    type: "approval",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Approved discount",
    target: "VIP customer · 15% on annual plan",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "iPhone 15 Pro",
    browser: "Staffbix iOS app",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0022",
    at: "2026-05-06T19:48:33Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Prompt injection detected",
    target: "Cyrus (Customer Support) · request blocked",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "blocked",
  },
  {
    id: "log_0023",
    at: "2026-05-06T15:04:22Z",
    type: "admin",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Connected integration",
    target: "Shopify Admin API · northway-goods.myshopify.com",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0024",
    at: "2026-05-06T09:31:17Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Eva",
    actorMeta: "Executive Assistant",
    action: "Triaged inbox · 47 emails",
    target: "Now: 4 · Today: 11 · This week: 32",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0025",
    at: "2026-05-05T22:11:09Z",
    type: "auth",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Failed OTP · 1 of 5 attempts",
    ip: "203.0.113.42",
    city: "Singapore",
    region: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    flag: "🇸🇬",
    device: "Unknown",
    browser: "Chrome 124",
    language: "EN",
    result: "failed",
  },
  {
    id: "log_0026",
    at: "2026-05-05T16:48:55Z",
    type: "admin",
    actorKind: "human",
    actorName: "Alex Morgan",
    actorMeta: "Owner",
    action: "Updated spending cap",
    target: "Adi (Ad Manager) · daily $150 → $200",
    ip: "78.182.42.118",
    city: "Istanbul",
    region: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Pro · 14-inch",
    browser: "Chrome 124",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0027",
    at: "2026-05-05T08:00:00Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Weekly executive summary sent",
    target: "test@mail.com + 1 recipient",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0028",
    at: "2026-05-04T14:22:18Z",
    type: "approval",
    actorKind: "human",
    actorName: "Ayşe Nehir",
    actorMeta: "Admin",
    action: "Approved campaign edit",
    target: "Iris (Inbound Sales) · email sequence change",
    ip: "94.55.182.27",
    city: "Ankara",
    region: "Ankara",
    country: "Türkiye",
    countryCode: "TR",
    flag: "🇹🇷",
    device: "MacBook Air",
    browser: "Safari 17.4",
    language: "TR",
    result: "success",
  },
  {
    id: "log_0029",
    at: "2026-05-04T10:14:33Z",
    type: "ai-action",
    actorKind: "ai",
    actorName: "Bea",
    actorMeta: "Bookkeeping Assistant",
    action: "Categorized 41 expenses",
    target: "Stripe + bank · 39 auto · 2 flagged",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
  {
    id: "log_0030",
    at: "2026-05-04T07:48:11Z",
    type: "system",
    actorKind: "system",
    actorName: "Platform",
    action: "Worker paused",
    target: "Pia (PR Manager) · manual pause by owner",
    ip: "10.42.0.5",
    city: "Frankfurt",
    region: "Hessen",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    device: "Server",
    browser: "Edge runtime",
    language: "EN",
    result: "success",
  },
];

export const LOG_TYPES: { key: LogType | "all"; label: string }[] = [
  { key: "all", label: "All" },
  { key: "auth", label: "Auth" },
  { key: "ai-action", label: "AI actions" },
  { key: "admin", label: "Admin" },
  { key: "approval", label: "Approvals" },
  { key: "system", label: "System" },
];

export function formatLogTime(iso: string): { date: string; time: string } {
  const d = new Date(iso);
  const date = d.toLocaleDateString("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
  });
  const time = d.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
  return { date, time };
}
