export type HiredWorkerStatus = "online" | "idle" | "paused";

export type HiredWorker = {
  id: string;
  initials: string;
  name: string;
  role: string;
  roleSlug: string;
  category: string;
  status: HiredWorkerStatus;
  channels: string[];
  languages: string[];
  approvalMode: "Automatic" | "Approval required" | "Suggestion only";
  hiredOn: string;
  messages7d: number;
  approvals7d: number;
  voiceMatch: number;
  schedule: string;
};

export const HIRED_WORKERS: HiredWorker[] = [
  {
    id: "wrk_cs_4nq3",
    initials: "CS",
    name: "Cyrus",
    role: "Customer Support",
    roleSlug: "customer-support",
    category: "Customer-facing",
    status: "online",
    channels: ["Web", "WhatsApp", "Email"],
    languages: ["EN", "TR", "DE"],
    approvalMode: "Approval required",
    hiredOn: "Mar 12, 2026",
    messages7d: 1342,
    approvals7d: 28,
    voiceMatch: 98,
    schedule: "24/7",
  },
  {
    id: "wrk_is_8qr2",
    initials: "IS",
    name: "Iris",
    role: "Inbound Sales Closer",
    roleSlug: "inbound-sales",
    category: "Sales",
    status: "online",
    channels: ["Web", "Email"],
    languages: ["EN"],
    approvalMode: "Approval required",
    hiredOn: "Mar 14, 2026",
    messages7d: 412,
    approvals7d: 41,
    voiceMatch: 96,
    schedule: "Mon–Fri 09–18 CET",
  },
  {
    id: "wrk_sm_1zk7",
    initials: "SM",
    name: "Soren",
    role: "Social Media Manager",
    roleSlug: "social-media",
    category: "Marketing",
    status: "online",
    channels: ["IG", "X", "FB", "LinkedIn"],
    languages: ["EN", "TR"],
    approvalMode: "Approval required",
    hiredOn: "Mar 17, 2026",
    messages7d: 86,
    approvals7d: 22,
    voiceMatch: 99,
    schedule: "Mon–Fri 09–18 CET",
  },
  {
    id: "wrk_se_5fa9",
    initials: "SE",
    name: "Sage",
    role: "SEO Specialist",
    roleSlug: "seo-specialist",
    category: "Marketing",
    status: "online",
    channels: ["WordPress", "Shopify"],
    languages: ["EN", "TR"],
    approvalMode: "Approval required",
    hiredOn: "Mar 20, 2026",
    messages7d: 0,
    approvals7d: 14,
    voiceMatch: 97,
    schedule: "Continuous",
  },
  {
    id: "wrk_cw_2hp8",
    initials: "CW",
    name: "Cora",
    role: "Content Writer",
    roleSlug: "content-writer",
    category: "Marketing",
    status: "idle",
    channels: ["CMS", "Email"],
    languages: ["EN"],
    approvalMode: "Approval required",
    hiredOn: "Mar 24, 2026",
    messages7d: 0,
    approvals7d: 9,
    voiceMatch: 99,
    schedule: "Continuous",
  },
  {
    id: "wrk_em_9bt4",
    initials: "EM",
    name: "Ezra",
    role: "Email Marketer",
    roleSlug: "email-marketer",
    category: "Marketing",
    status: "online",
    channels: ["Email"],
    languages: ["EN", "TR"],
    approvalMode: "Approval required",
    hiredOn: "Mar 28, 2026",
    messages7d: 2840,
    approvals7d: 5,
    voiceMatch: 98,
    schedule: "Mon, Wed, Fri 08–17 CET",
  },
  {
    id: "wrk_bk_3mn1",
    initials: "BK",
    name: "Bea",
    role: "Bookkeeping Assistant",
    roleSlug: "bookkeeping",
    category: "Finance",
    status: "idle",
    channels: ["Stripe", "Bank"],
    languages: ["EN", "TR"],
    approvalMode: "Approval required",
    hiredOn: "Apr 02, 2026",
    messages7d: 0,
    approvals7d: 11,
    voiceMatch: 99,
    schedule: "Daily 06–08 CET",
  },
  {
    id: "wrk_ea_6dl5",
    initials: "EA",
    name: "Eva",
    role: "Executive Assistant",
    roleSlug: "exec-assistant",
    category: "Operations",
    status: "online",
    channels: ["Email", "Calendar"],
    languages: ["EN", "TR"],
    approvalMode: "Automatic",
    hiredOn: "Apr 05, 2026",
    messages7d: 240,
    approvals7d: 0,
    voiceMatch: 100,
    schedule: "Mon–Fri 08–20 CET",
  },
  {
    id: "wrk_ba_7vz2",
    initials: "BA",
    name: "Beck",
    role: "Business Analyst",
    roleSlug: "business-analyst",
    category: "Leadership",
    status: "online",
    channels: ["Internal"],
    languages: ["EN"],
    approvalMode: "Suggestion only",
    hiredOn: "Apr 09, 2026",
    messages7d: 14,
    approvals7d: 7,
    voiceMatch: 99,
    schedule: "Daily 06–07 CET",
  },
  {
    id: "wrk_pr_0fb3",
    initials: "PR",
    name: "Pia",
    role: "PR Manager",
    roleSlug: "pr-manager",
    category: "Marketing",
    status: "paused",
    channels: ["Email"],
    languages: ["EN"],
    approvalMode: "Approval required",
    hiredOn: "Apr 12, 2026",
    messages7d: 0,
    approvals7d: 2,
    voiceMatch: 99,
    schedule: "Paused since May 4",
  },
];

export function findHiredWorker(id: string): HiredWorker | undefined {
  return HIRED_WORKERS.find((w) => w.id === id);
}

export const APPROVAL_MODES = [
  "Automatic",
  "Approval required",
  "Suggestion only",
] as const;

export const SCHEDULES = [
  "Continuous (24/7)",
  "Mon–Fri 09–18 CET",
  "Mon–Fri 08–20 CET",
  "Mon, Wed, Fri 08–17 CET",
  "Daily 06–08 CET",
  "Manual only",
] as const;

export const ALL_CHANNELS = [
  "Web",
  "WhatsApp",
  "Telegram",
  "Email",
  "Phone",
  "IG",
  "X",
  "FB",
  "LinkedIn",
  "TikTok",
  "YouTube",
  "Pinterest",
  "WordPress",
  "Shopify",
  "Stripe",
  "Bank",
  "CMS",
  "Calendar",
  "Slack",
  "Internal",
] as const;
