import type { Metadata, Viewport } from "next";
import type { Locale } from "@/lib/i18n/config";
import { SITE_LOCALES, SITE_NAME, SITE_ORIGIN, localeUrl } from "./site";

/**
 * Site-wide viewport + theme-color. Exported from the root layout (or
 * inherited by any segment that doesn't override it). Next.js 15
 * separates `viewport` from `metadata` — `themeColor`, `colorScheme`,
 * and the viewport tag itself live here.
 *
 * The mint shade matches our hero CTA. Browsers paint the address-bar
 * + tab strip with this color on mobile (Chrome/Edge) and Safari iOS
 * PWA's status bar.
 */
export const siteViewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#34D399" },
    { media: "(prefers-color-scheme: dark)", color: "#0A0A0A" },
  ],
  colorScheme: "light dark",
};

/**
 * Build a fully-loaded Next.js `Metadata` object for a public page.
 * Emits:
 *   - title, description
 *   - canonical link  (matches the locale of the request)
 *   - hreflang `alternates.languages` for every supported locale
 *     plus `x-default` pointing at en
 *   - OpenGraph (site_name, type=website, locale, og:image)
 *   - Twitter card (summary_large_image, og:image)
 *   - robots: index/follow + max-snippet/max-image-preview hints
 *     (or noindex when `noIndex: true`)
 *
 * Pass `path` as the route under `/[lang]`. For the homepage pass
 * an empty string.
 */
export function buildPageMetadata(args: {
  locale: Locale;
  /** Route under /[lang], e.g. "pricing", "docs/api", "" for home. */
  path: string;
  title: string;
  description: string;
  /** Absolute URL of OG image. Falls back to /icon.png. */
  ogImage?: string;
  /** Set true for /login, /signup, /reset, /verify, /accept etc. */
  noIndex?: boolean;
  /** Override OG type — defaults to "website". Use "article" for changelog/blog. */
  ogType?: "website" | "article";
  /** Optional publishedTime / modifiedTime for og:article. */
  publishedTime?: string;
  modifiedTime?: string;
  /** Page-specific keywords. Strictly page-scoped — no site-level merge. */
  keywords?: readonly string[];
}): Metadata {
  const {
    locale,
    path,
    title,
    description,
    ogImage,
    noIndex = false,
    ogType = "website",
    publishedTime,
    modifiedTime,
    keywords,
  } = args;

  const url = localeUrl(locale, path);
  const fullTitle = title.includes(SITE_NAME) ? title : `${title} · ${SITE_NAME}`;
  const image = ogImage ?? `${SITE_ORIGIN}/icon.png`;

  // hreflang alternates: every locale's version of this same path, plus
  // x-default pointing at en (Google convention for "no language match
  // → serve English").
  const languages: Record<string, string> = {};
  for (const loc of SITE_LOCALES) {
    languages[loc] = localeUrl(loc, path);
  }
  languages["x-default"] = localeUrl("en", path);

  // Keywords are now strictly page-specific — no site-level fallback
  // merge. Each page must declare its own set in its page-copy.ts
  // metadata block so the strings flow through the i18n translation
  // pipeline (one English source string → 23 localized variants in
  // generated-copy-translations.ts).
  //
  // When `keywords` is undefined we emit no <meta name="keywords">
  // tag at all (cleaner than a generic catch-all that dilutes
  // signal). Bing/Yandex/Baidu prefer specific over generic.
  const finalKeywords =
    keywords && keywords.length > 0 ? [...keywords] : undefined;

  return {
    metadataBase: new URL(SITE_ORIGIN),
    title: fullTitle,
    description,
    applicationName: SITE_NAME,
    authors: [{ name: SITE_NAME, url: SITE_ORIGIN }],
    creator: SITE_NAME,
    publisher: SITE_NAME,
    keywords: finalKeywords,
    alternates: {
      canonical: url,
      languages,
      types: {
        "application/rss+xml": [
          {
            url: `${SITE_ORIGIN}/rss.xml`,
            title: `${SITE_NAME} — changelog`,
          },
        ],
      },
    },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-snippet": -1,
            "max-image-preview": "large",
            "max-video-preview": -1,
          },
        },
    // Search-engine site-ownership verification meta tags. One-time
    // codes generated by Bing Webmaster Tools and Yandex Webmaster.
    // Google verification is handled by gtag.js (no meta needed) +
    // the DNS TXT record submitted in Search Console.
    verification: {
      yandex: "dff8f19f0caccf27",
      other: {
        "msvalidate.01": "CF96D9BFB6DCE33CFE5FDE9BE9FC453A",
      },
    },
    openGraph: {
      type: ogType,
      url,
      siteName: SITE_NAME,
      title: fullTitle,
      description,
      locale,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: SITE_NAME,
        },
      ],
      ...(ogType === "article" && publishedTime
        ? { publishedTime, modifiedTime: modifiedTime ?? publishedTime }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      site: "@staffbix",
      creator: "@staffbix",
      title: fullTitle,
      description,
      images: [image],
    },
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    other: {
      "format-detection": "telephone=no",
      // GEO targeting — Staffbix is a global SaaS so we declare worldwide
      // coverage. Yandex + Bing + Baidu use these tags; Google ignores
      // them but they cost nothing. ICBM is intentionally omitted (a
      // single coordinate would mislead for a global service — better
      // empty than wrong, per the SlavFans `0.0, 0.0` anti-pattern).
      "geo.placename": "Worldwide",
      "geo.region": "001", // ISO 3166-1 numeric for the whole world
    },
  };
}
