import type { Tool } from "../types";
import { draftOutreachEmail } from "@/lib/sales/outreach";

/**
 * queue_outreach_email — wrap Sprint 9's `draftOutreachEmail` runtime
 * as a tool the model can call. The runtime:
 *
 *   1. Loads the lead from DB
 *   2. Spins up a chat turn with the SDR worker's prompt + lead notes
 *   3. Produces a personalized subject + body
 *   4. Persists as a worker_action(kind='email_send') in the right
 *      autonomy state (auto = sent immediately by the dispatch worker,
 *      approve = goes to the Approval Center)
 *
 * Suggest-mode: the underlying runtime always creates a draft action;
 * we refuse here at the tool boundary so suggest-mode workers don't
 * accidentally pre-populate the inbox with proposals they shouldn't be
 * pre-populating. The model is asked to inline the draft in its
 * conversational reply instead.
 */

export const queueOutreachEmailTool: Tool = {
  name: "queue_outreach_email",
  description:
    "Draft + queue a personalized cold-outreach email to a lead you've already registered via create_outreach_lead. Pass the leadId. The email body is generated by the worker's own prompt — pass `promptOverride` to steer it (e.g., 'Lead with their Series B news; ask if their support SLA is a priority').",
  parameters: {
    type: "object",
    properties: {
      leadId: { type: "string", description: "Lead row id from create_outreach_lead." },
      promptOverride: {
        type: "string",
        description:
          "Optional steering note for the draft. Include any enrichment signals you want the email to reference (Series B, recent post, opening new locations). Leave empty to use the worker's defaults.",
      },
    },
    required: ["leadId"],
    additionalProperties: false,
  },
  async execute(args, ctx) {
    const leadId = String(args.leadId);
    const promptOverride = args.promptOverride
      ? String(args.promptOverride)
      : undefined;

    if (!/^[0-9a-f-]{36}$/.test(leadId)) {
      return { ok: false, refused: true, reason: "leadId is not a UUID." };
    }

    if (ctx.autonomy === "suggest") {
      return {
        ok: false,
        refused: true,
        reason:
          "Worker is in 'suggest' mode — inline the proposed subject+body in your reply instead of queueing. The owner sends it manually from the dashboard.",
      };
    }

    try {
      const result = await draftOutreachEmail({
        tenantId: ctx.tenantId,
        workerId: ctx.workerId,
        leadId,
        promptOverride,
      });
      return {
        ok: true,
        data: {
          actionId: result.actionId,
          subject: result.subject,
          conversationId: result.conversationId,
          willSend: ctx.autonomy === "auto" ? "immediately" : "after owner approval",
          autonomy: ctx.autonomy,
        },
      };
    } catch (err) {
      const e = err as { code?: string; message?: string };
      return {
        ok: false,
        refused: true,
        reason: `Couldn't queue the outreach email: ${e.message ?? String(err)}${e.code ? ` [${e.code}]` : ""}`,
      };
    }
  },
};
