import { type NextRequest } from "next/server";
import { and, eq, desc } from "drizzle-orm";
import { db } from "@/lib/db/client";
import {
  tenants,
  workers,
  conversations,
  messages,
} from "@/lib/db/schema";
import { streamChatReply, chatReply } from "@/lib/ai/chat";
import { readJson, normalizeEmail, getClientIp, getUserAgent } from "@/lib/auth/request";
import { rateLimitOr429 } from "@/lib/auth/rate-limit-route";
import { createPending, recordAuto } from "@/lib/approvals/runtime";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Per-session rate-limiting for widget traffic lands in Sprint 7 alongside
// the WhatsApp + IG channels (when an abuse vector emerges that justifies
// the bucket-config work). Sprint 5 ships the route without a limiter.

interface Body {
  tenantSlug?: string;
  workerId?: string;
  /** Opaque widget session id — client-generated, stable per browser session. */
  sessionId?: string;
  message?: string;
  /** Optional customer self-identification. */
  customer?: { name?: string; email?: string };
}

/**
 * POST /api/widget/message
 *
 * Public endpoint — no auth header (it's called by the embeddable widget
 * on a customer's website). Auth-by-routing: we look up the tenant from
 * the `tenantSlug` body field and the worker from `workerId`. If the
 * worker doesn't belong to the tenant (or the worker isn't `active`,
 * or the channel isn't web) we 404 to avoid revealing which slugs/IDs
 * are valid.
 *
 * Rate-limited per (tenantId, sessionId) — 30 messages per 15 min.
 *
 * Returns SSE: a stream of `data: { delta: "..." }` events terminated
 * by `data: { done: true, conversationId, messageId }`.
 */
export async function POST(req: NextRequest): Promise<Response> {
  const body = await readJson<Body>(req);
  if (!body) return jsonError("Invalid JSON", 400);

  const tenantSlug = typeof body.tenantSlug === "string" ? body.tenantSlug : "";
  const workerId = typeof body.workerId === "string" ? body.workerId : "";
  const sessionId = typeof body.sessionId === "string" ? body.sessionId : "";
  const message = typeof body.message === "string" ? body.message.trim() : "";

  if (!tenantSlug || !workerId || !sessionId || !message) {
    return jsonError("tenantSlug, workerId, sessionId, message are all required", 400);
  }

  // Two limiters, deliberately. `sessionId` is generated by the browser,
  // so the per-session bucket alone is trivially bypassed by rotating it
  // — and every request that gets through costs us an OpenAI call on an
  // unauthenticated endpoint. The per-IP bucket is the one an abuser
  // cannot rotate without also rotating network origin.
  const ipW = getClientIp(req);
  const uaW = getUserAgent(req);
  const throttled =
    (ipW
      ? await rateLimitOr429("widgetIp", `widget-ip:${ipW}`, {
          ip: ipW,
          userAgent: uaW,
          route: "POST /api/widget/message",
        })
      : null) ??
    (await rateLimitOr429("chat", `widget:${tenantSlug}:${sessionId}`, {
      ip: ipW,
      userAgent: uaW,
      route: "POST /api/widget/message",
    }));
  if (throttled) {
    // Translate the JSON 429 to a widget-friendly response (still 429,
    // still has Retry-After; just adds CORS headers so the embedded
    // widget can read it).
    return new Response(await throttled.text(), {
      status: 429,
      headers: {
        "Content-Type": "application/json",
        "Retry-After": throttled.headers.get("Retry-After") ?? "60",
        "Access-Control-Allow-Origin": "*",
      },
    });
  }
  if (message.length > 4000) {
    return jsonError("Message too long (max 4000 chars)", 413);
  }
  if (!/^[0-9a-f-]{36}$/.test(workerId)) {
    return jsonError("Worker not found", 404);
  }

  // Tenant + worker lookup
  const [tenantRow] = await db
    .select({ id: tenants.id, status: tenants.status })
    .from(tenants)
    .where(eq(tenants.slug, tenantSlug))
    .limit(1);
  if (!tenantRow) return jsonError("Worker not found", 404);
  // Suspended / canceled tenants don't get to serve widget traffic.
  if (tenantRow.status !== "trialing" && tenantRow.status !== "active") {
    return jsonError("Service unavailable", 503);
  }

  const [worker] = await db
    .select()
    .from(workers)
    .where(and(eq(workers.id, workerId), eq(workers.tenantId, tenantRow.id)))
    .limit(1);
  if (!worker) return jsonError("Worker not found", 404);
  if (worker.status !== "active") return jsonError("Worker is not active", 409);
  // Case-insensitive: storage SHOULD already be lowercase (hireWorker
  // normalizes), but stay tolerant of any legacy rows imported via a
  // future migration that may carry title-cased channel labels.
  const channelsLower = worker.channels.map((c) => c.toLowerCase());
  if (!channelsLower.includes("web")) {
    return jsonError("Worker is not wired to the web channel", 409);
  }

  // Normalize the customer hints — never trust the widget payload as-is.
  const customer: Record<string, unknown> | undefined =
    body.customer && typeof body.customer === "object"
      ? {
          name:
            typeof body.customer.name === "string"
              ? body.customer.name.slice(0, 120)
              : undefined,
          email: normalizeEmail(body.customer.email) ?? undefined,
        }
      : undefined;

  // Find-or-create conversation
  let convoId: string;
  {
    const existing = await db
      .select({ id: conversations.id })
      .from(conversations)
      .where(
        and(
          eq(conversations.tenantId, tenantRow.id),
          eq(conversations.workerId, worker.id),
          eq(conversations.channel, "web"),
          eq(conversations.externalId, sessionId),
        ),
      )
      .limit(1);
    if (existing[0]) {
      convoId = existing[0].id;
    } else {
      const [created] = await db
        .insert(conversations)
        .values({
          tenantId: tenantRow.id,
          workerId: worker.id,
          channel: "web",
          externalId: sessionId,
          customer: customer ?? null,
          status: "open",
        })
        .returning({ id: conversations.id });
      convoId = created.id;
    }
  }

  // Persist user message
  await db.insert(messages).values({
    tenantId: tenantRow.id,
    conversationId: convoId,
    role: "user",
    content: message,
  });

  // Pull history (last 20)
  const history = await db
    .select({ role: messages.role, content: messages.content })
    .from(messages)
    .where(eq(messages.conversationId, convoId))
    .orderBy(desc(messages.createdAt))
    .limit(20);
  history.reverse();

  // Autonomy gate (PRD §1.5). The worker either acts on its own (auto)
  // or generates a draft that must be human-approved before the
  // customer ever sees it (approve / suggest).
  //
  // In `auto` we stream the AI reply directly to the customer as it
  // generates — same UX as Sprint 5.
  //
  // In `approve` / `suggest` we run the chat non-streaming (so the AI
  // text doesn't leak to the customer's browser), persist the assistant
  // draft, create a pending worker_action, and reply to the customer
  // with a fixed holding message. Owner gets pushed via Expo, approves
  // in the Approval Center, and the dispatcher posts the reply when
  // the customer returns.
  const chatContext = {
    tenantId: tenantRow.id,
    workerId: worker.id,
    workerName: worker.name,
    roleSlug: worker.roleSlug,
    customInstructions: worker.customInstructions,
    conversationId: convoId,
    modelPin: worker.modelPin,
  };
  const historyForChat = history
    .filter((m) => m.role === "user" || m.role === "assistant" || m.role === "human_agent")
    .map((m) => ({
      role: m.role as "user" | "assistant" | "human_agent",
      content: m.content,
    }));

  const encoder = new TextEncoder();
  let readable: ReadableStream<Uint8Array>;

  if (worker.autonomy === "auto") {
    const { stream, done } = streamChatReply({
      context: chatContext,
      history: historyForChat,
      userMessage: message,
    });
    readable = new ReadableStream<Uint8Array>({
      async start(controller) {
        function send(obj: unknown) {
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
        }
        try {
          for await (const delta of stream) send({ delta });
          const result = await done;
          // Persist assistant message
          const [assistantRow] = await db
            .insert(messages)
            .values({
              tenantId: tenantRow.id,
              conversationId: convoId,
              role: "assistant",
              content: result.text,
              citedChunkIds: result.citedChunkIds,
              model: result.model,
              promptTokens: result.promptTokens,
              completionTokens: result.completionTokens,
              latencyMs: result.latencyMs,
            })
            .returning({ id: messages.id });
          // Record the auto action for the audit trail.
          await recordAuto({
            tenantId: tenantRow.id,
            workerId: worker.id,
            conversationId: convoId,
            draftMessageId: assistantRow.id,
            kind: "web_reply",
            content: result.text,
          });
          await db
            .update(conversations)
            .set({ lastMessageAt: new Date(), updatedAt: new Date() })
            .where(eq(conversations.id, convoId));
          send({
            done: true,
            conversationId: convoId,
            messageId: assistantRow.id,
            latencyMs: result.latencyMs,
          });
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          send({ error: msg.slice(0, 200) });
        } finally {
          controller.close();
        }
      },
    });
  } else {
    // Approve / suggest path: generate the draft, persist, queue for
    // approval, send a holding message to the customer.
    const HOLDING_TEXT =
      "Thanks for your message. A teammate is reviewing this and will follow up shortly.";

    readable = new ReadableStream<Uint8Array>({
      async start(controller) {
        function send(obj: unknown) {
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
        }
        try {
          // Generate the draft NON-STREAMING so the AI output never
          // reaches the customer's browser.
          const result = await chatReply({
            context: chatContext,
            history: historyForChat,
            userMessage: message,
          });
          const [assistantRow] = await db
            .insert(messages)
            .values({
              tenantId: tenantRow.id,
              conversationId: convoId,
              role: "assistant",
              content: result.text,
              citedChunkIds: result.citedChunkIds,
              model: result.model,
              promptTokens: result.promptTokens,
              completionTokens: result.completionTokens,
              latencyMs: result.latencyMs,
            })
            .returning({ id: messages.id });
          await createPending({
            tenantId: tenantRow.id,
            workerId: worker.id,
            conversationId: convoId,
            draftMessageId: assistantRow.id,
            kind: "web_reply",
            content: result.text,
          });
          await db
            .update(conversations)
            .set({
              lastMessageAt: new Date(),
              updatedAt: new Date(),
              status: "awaiting_human",
            })
            .where(eq(conversations.id, convoId));

          send({ delta: HOLDING_TEXT });
          send({
            done: true,
            conversationId: convoId,
            messageId: assistantRow.id,
            awaitingApproval: true,
          });
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          send({ error: msg.slice(0, 200) });
        } finally {
          controller.close();
        }
      },
    });
  }

  return new Response(readable, {
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      // CORS — widget runs on tenant's own domain. Wildcard is acceptable
      // because the auth model here is tenantSlug + workerId pair, not
      // origin-bound.
      "Access-Control-Allow-Origin": "*",
    },
  });
}

export async function OPTIONS(): Promise<Response> {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "content-type",
      "Access-Control-Max-Age": "86400",
    },
  });
}

function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
